// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Time is an autogenerated mock type for the Time type
type Time struct {
	mock.Mock
}

// Now provides a mock function with given fields: timeGMT
func (_m *Time) Now(timeGMT *int) time.Time {
	ret := _m.Called(timeGMT)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(*int) time.Time); ok {
		r0 = rf(timeGMT)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
