// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	container "fyne.io/fyne/v2/container"

	mock "github.com/stretchr/testify/mock"
)

// IndodaxGUI is an autogenerated mock type for the IndodaxGUI type
type IndodaxGUI struct {
	mock.Mock
}

// Show provides a mock function with given fields:
func (_m *IndodaxGUI) Show() *container.AppTabs {
	ret := _m.Called()

	var r0 *container.AppTabs
	if rf, ok := ret.Get(0).(func() *container.AppTabs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*container.AppTabs)
		}
	}

	return r0
}

// ShowV2 provides a mock function with given fields:
func (_m *IndodaxGUI) ShowV2() *container.Split {
	ret := _m.Called()

	var r0 *container.Split
	if rf, ok := ret.Get(0).(func() *container.Split); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*container.Split)
		}
	}

	return r0
}
