// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	repository "github.com/FAT/repository"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Postgres provides a mock function with given fields:
func (_m *Storage) Postgres() (*repository.Queries, error) {
	ret := _m.Called()

	var r0 *repository.Queries
	if rf, ok := ret.Get(0).(func() *repository.Queries); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Queries)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
