// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CLICore is an autogenerated mock type for the CLICore type
type CLICore struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *CLICore) Run() {
	_m.Called()
}
