// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
)

type Order struct {
	OrderID    int64        `json:"order_id"`
	OrderPrice string       `json:"order_price"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
