// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// maUpdater is an autogenerated mock type for the maUpdater type
type maUpdater struct {
	mock.Mock
}

// InitPeriod provides a mock function with given fields:
func (_m *maUpdater) InitPeriod() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Update provides a mock function with given fields: v
func (_m *maUpdater) Update(v float64) float64 {
	ret := _m.Called(v)

	var r0 float64
	if rf, ok := ret.Get(0).(func(float64) float64); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Valid provides a mock function with given fields:
func (_m *maUpdater) Valid() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
