package constant

var Debug string = "debug"
var Staging string = "staging"
var TrenMacdBullish string = "Bullish"
var TrenMacdBearish string = "Bearish"
var TrenMacdBullishDivergence string = "Bullish Divergence"
var TrenMacdBearishDivergence string = "Bearish Divergence"
var TrenMacdHiddenBullishDivergence string = "Hidden Bullish Divergence"
var TrenMacdHiddenHiddenBearishDivergence string = "Hidden Bearish Divergence"
var ChangeTrendFromBearishToBullish string = "Bearish To Bullis"
var ChangeTrendFromBullishToBearish string = "Bullish To Bearish"
var INODAX_TRADE_METHOD string = "trade"
var INODAX_GET_INFO_METHOD string = "getInfo"
var INODAX_ORDER_HISTORY_METHOD string = "orderHistory"
