definitions:
  models.MarketHistory:
    properties:
      close:
        items:
          type: number
        type: array
      high:
        items:
          type: number
        type: array
      low:
        items:
          type: number
        type: array
      open:
        items:
          type: number
        type: array
    type: object
  models.MarketHistoryPayload:
    properties:
      from:
        type: integer
      symbol:
        type: string
      timeFrame:
        type: integer
      to:
        type: integer
    type: object
  models.OrderPayload:
    properties:
      order_crypto:
        type: string
      order_price:
        type: number
      order_type:
        type: string
    type: object
  repository.Order:
    properties:
      created_at:
        type: string
      order_crypto:
        type: string
      order_id:
        type: integer
      order_price:
        type: number
      order_status:
        type: string
      order_type:
        type: string
      updated_at:
        type: string
    type: object
  wrapper.Response:
    properties:
      location:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /indodax/market_history:
    post:
      consumes:
      - application/json
      description: get market history
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: market history payload
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.MarketHistoryPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MarketHistory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/wrapper.Response'
      summary: Show an market history data
  /indodax/order:
    post:
      consumes:
      - application/json
      description: Create new order data to database
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Order payload
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.OrderPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wrapper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/wrapper.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/wrapper.Response'
      summary: Create order data
  /indodax/order/{id}:
    delete:
      description: Delete order Data by ID
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wrapper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/wrapper.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.Response'
      summary: Delete order
    get:
      consumes:
      - application/json
      description: get order by ID
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/wrapper.Response'
      summary: Show an order data
  /indodax/order/data:
    get:
      consumes:
      - application/json
      description: get orders
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: page offset
        in: query
        name: page
        type: integer
      - description: data size
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Order'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/wrapper.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.Response'
      summary: List order
swagger: "2.0"
