// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GUI is an autogenerated mock type for the GUI type
type GUI struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *GUI) Run() {
	_m.Called()
}

// RunV2 provides a mock function with given fields:
func (_m *GUI) RunV2() {
	_m.Called()
}
