// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/FAT/repository"
)

// Indodax is an autogenerated mock type for the Indodax type
type Indodax struct {
	mock.Mock
}

// Order provides a mock function with given fields: ctx, arg
func (_m *Indodax) Order(ctx *gin.Context, arg repository.CreateOrderParams) (repository.Order, error) {
	ret := _m.Called(ctx, arg)

	var r0 repository.Order
	if rf, ok := ret.Get(0).(func(*gin.Context, repository.CreateOrderParams) repository.Order); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, repository.CreateOrderParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
